[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/stripe-webhook"
  to = "/.netlify/functions/stripe-webhook"
  status = 200
  force = true

[[redirects]]
  from = "/api/register-employer"
  to = "/.netlify/functions/register-employer"
  status = 200
  force = true

[[redirects]]
  from = "/api/free-employer"
  to = "/.netlify/functions/free-employer"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
